### ISSUE TITLE
meleeAttack & rangedAttack: Dokumentation der Modifikatoren reparieren & Tooltip ergänzen

### ISSUE THREAD

**Issue by phylll** [phylll/mychs-macro-magic#6]
Angriffsmodifikatoren neben der Privattabelle für den kontrollierenden Spieler und GM auch im Tooltip dokumentieren.

**Comment by michael-buschbeck** [comment]
Die Privattabelle hat (bei mir) offenbar auch einen Bug und zeigt viel mehr an als das, was tatsächlich in die Modifikatoren eingeflossen ist:

![image](https://user-images.githubusercontent.com/5649035/116155119-f69ce400-a6e9-11eb-813c-7c96256c7c19.png)

Erzeugt bei einem Angriff von hinten. Aufruf, der Vollständigkeit halber:

![image](https://user-images.githubusercontent.com/5649035/116155213-17653980-a6ea-11eb-9b9c-a9d64bdc5f44.png)

**Comment by phylll** [comment]
Spannend. Bei meinen Tests ist das nicht passiert, muss ich mal im Testspiel anschauen. Was ich da mache, ist im Dropdown die verschiedenen Kombinationen von Boni/Mali als Produkt von Primzahlen zu codieren. Das wird dann ausgewertet mit `!mmm   if semiAutoModCode % 19 == 0` usw. -- und in deinem Fall kommt ein Wert raus, der offenbar durch alle Primzahlen zwischen 19 und 2 sauber teilbar ist?!

![image](https://user-images.githubusercontent.com/20493964/116156130-619aea80-a6eb-11eb-956f-8c8b3720368f.png)

**Comment by michael-buschbeck** [comment]
Hah, clever!

`0` wäre so ein Wert – oder halt irgendetwas, was MMM nicht als Zahl interpretieren kann und das deswegen beim Modulo-Operator zu `0` wird.

Die Tabelle passt tatsächlich auch zum berechneten Endergebnis: Die Summe aller Einträge ist `+2`.

Ich glaube, ich habe bei den Drop-downs überall den Default genommen.

**Comment by phylll** [comment]
Tatsache. Da steht eine `0` im Code, wo lt. der Exceltabelle eben eine `1` stehen sollte (für einen normalen Angriff ohne irgendeinen dieser Modifikatoren aus den Dropdown-Boxen). Keine Ahnung wann und wie die da reingerutscht ist, nachdem ich das getestet hatte. Ich bau noch den Tooltip.

Vielen Dank!

**Comment by michael-buschbeck** [comment]
Die Tabelle ist natürlich toll – ich hatte nur nicht realisiert, dass sie schon die effektiven Modifikatoren anzeigt. Tooltip ist fab das Tüpfelchen auf dem I :)

**Comment by phylll** [comment]
Tooltip war einfacher als ich dachte, habe ich heute früh auch noch schnell gebaut für alle drei Skripte. Muss ich nur nochmal ein bisschen testen, bevor der PR kommt. Viel copy & paste, da kann ja immer mal was passieren...
